from projects.neuroimaging_pipelines.pipeline import PipelinefMRI

paths = {'input_path': '/home/brainlab/Desktop/Rudas/Data/hcp_100/fmri',
         'template_spm_path': '/home/brainlab/Desktop/Rudas/Data/Parcellation/TPM.nii',
         'mcr_path': '/home/brainlab/Desktop/Rudas/Tools/MCR/v713',
         'spm_path': '/home/brainlab/Desktop/Rudas/Tools/spm12_r7487/spm12/run_spm12.sh',
         'image_parcellation_path': [
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Auditory/Auditory_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Auditory/Auditory_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Auditory/Auditory_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/CinguloOperc/CinguloOperc_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/CinguloOperc/CinguloOperc_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/CinguloOperc/CinguloOperc_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/CinguloParietal/CinguloParietal_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/CinguloParietal/CinguloParietal_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Default/Default_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Default/Default_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Default/Default_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/DorsalAttn/DorsalAttn_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/DorsalAttn/DorsalAttn_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/DorsalAttn/DorsalAttn_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/FrontoParietal/FrontoParietal_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/FrontoParietal/FrontoParietal_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/FrontoParietal/FrontoParietal_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/RetrosplenialTemporal/RetrosplenialTemporal_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/RetrosplenialTemporal/RetrosplenialTemporal_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/RetrosplenialTemporal/RetrosplenialTemporal_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Salience/Salience_parcellation_3.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Salience/Salience_parcellation_4.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/SMhand/SMhand_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/SMhand/SMhand_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/SMhand/SMhand_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/SMmouth/SMmouth_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/SMmouth/SMmouth_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/SMmouth/SMmouth_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/VentralAttn/VentralAttn_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/VentralAttn/VentralAttn_parcellation_5.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/VentralAttn/VentralAttn_parcellation_6.nii',
             # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Visual/Visual_parcellation_4.nii',
             '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Visual/Visual_parcellation_5.nii'],
         # '/home/brainlab/Desktop/Rudas/Data/Parcellation/rsn_parcellations/Visual/Visual_parcellation_6.nii'],
         'labels_parcellation_path': None,
         'mask_mni_path': '/home/brainlab/Desktop/Rudas/Data/Propofol/MNI152_T1_2mm_brain_mask.nii.gz'}

parameters = {'fwhm': 8,
              'tr': 2,
              'init_volume': 6,
              'iso_size': 2,
              'low_pass': 0.1,
              'high_pass': 0.01}

subject_list = [#'899885_3T_rfMRI_REST1_unproc',
                #'857263_3T_rfMRI_REST1_unproc',
                #'856766_3T_rfMRI_REST1_unproc',
                '792564_3T_rfMRI_REST1_unproc']
                #'756055_3T_rfMRI_REST1_unproc',
                #'751348_3T_rfMRI_REST1_unproc',
                #'672756_3T_rfMRI_REST1_unproc',
                #'654754_3T_rfMRI_REST1_unproc',
                #'499566_3T_rfMRI_REST1_unproc',
                #'414229_3T_rfMRI_REST1_unproc',
                #'397760_3T_rfMRI_REST1_unproc',
                #'366446_3T_rfMRI_REST1_unproc',
                #'298051_3T_rfMRI_REST1_unproc',
                #'280739_3T_rfMRI_REST1_unproc',
                #'245333_3T_rfMRI_REST1_unproc',
                #'239944_3T_rfMRI_REST1_unproc',
                #'221319_3T_rfMRI_REST1_unproc',
                #'214423_3T_rfMRI_REST1_unproc',
                #'212318_3T_rfMRI_REST1_unproc',
                #'211720_3T_rfMRI_REST1_unproc']

pipeline = PipelinefMRI(paths=paths, parameters=parameters, subject_list=subject_list)
pipeline.run()
